/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LossEntry = IDL.Record({
  'loss' : IDL.Float64,
  'iteration' : IDL.Nat,
});
export const LossSurfacePoint = IDL.Record({
  'w1' : IDL.Float64,
  'w2' : IDL.Float64,
  'loss' : IDL.Float64,
});
export const StepResult = IDL.Record({
  'w1' : IDL.Float64,
  'w2' : IDL.Float64,
  'loss' : IDL.Float64,
  'gradientMagnitude' : IDL.Float64,
  'iteration' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getLossHistory' : IDL.Func([], [IDL.Vec(LossEntry)], ['query']),
  'getLossSurface' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LossSurfacePoint)],
      ['query'],
    ),
  'initialize' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
  'reset' : IDL.Func([], [], []),
  'step' : IDL.Func([IDL.Float64], [StepResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LossEntry = IDL.Record({ 'loss' : IDL.Float64, 'iteration' : IDL.Nat });
  const LossSurfacePoint = IDL.Record({
    'w1' : IDL.Float64,
    'w2' : IDL.Float64,
    'loss' : IDL.Float64,
  });
  const StepResult = IDL.Record({
    'w1' : IDL.Float64,
    'w2' : IDL.Float64,
    'loss' : IDL.Float64,
    'gradientMagnitude' : IDL.Float64,
    'iteration' : IDL.Nat,
  });
  
  return IDL.Service({
    'getLossHistory' : IDL.Func([], [IDL.Vec(LossEntry)], ['query']),
    'getLossSurface' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LossSurfacePoint)],
        ['query'],
      ),
    'initialize' : IDL.Func([IDL.Float64, IDL.Float64], [], []),
    'reset' : IDL.Func([], [], []),
    'step' : IDL.Func([IDL.Float64], [StepResult], []),
  });
};

export const init = ({ IDL }) => { return []; };